name: Deploy to Cloud Run

on:
  push:
    branches: [ "master", "main" ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: hello-cloudrun-yihexaplay-01
  REGION: northamerica-northeast1
  SERVICE_NAME: hello-cloudrun-service
  REPO_NAME: hello-cloudrun-repo
  IMAGE: northamerica-northeast1-docker.pkg.dev/hello-cloudrun-yihexaplay-01/hello-cloudrun-repo/hello-cloudrun-service:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/707164500119/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-cloud-run-deployer@hello-cloudrun-yihexaplay-01.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth
        run: gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t "$IMAGE" .

      - name: Push Docker image
        run: docker push "$IMAGE"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --image="$IMAGE" \
            --region="$REGION" \
            --platform=managed \
            --allow-unauthenticated \
            --quiet
